# Generated by Django 4.0.3 on 2022-10-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Address line'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Postal Code'),
        ),
    ]
