# Generated by Django 4.0.3 on 2022-10-18 06:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_address_newuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
