# Generated by Django 4.0.3 on 2022-10-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_newuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='photo',
            field=models.ImageField(default='photo/default-user-avatar.png', upload_to='photo/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Home Address'),
        ),
    ]
